version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: NPM build
          command: npm run build

  test:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: NPM install
          command: npm install
      - run:
          name: NPM test
          command: npm test

  final:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run: echo "All is done!"

workflows:
  double-workflow:
    jobs:
      - build
      - test
      - final:
          requires: 
            - build
            - test
